# Quotes to randomly display


QUOTES = r"""
"It's pronounced Testi Cee El... He's Chilean, you see."
"Tattoy is so cool!"
"Dale a tu cuerpo Alegría Macarena... EEEEH MACARENA!"
"You should really check out SPEEDFREAK at itch.io"
"Probame ÉSTA"
"DAMN!"
"No."
"Go home be a family man!"
"...One to the left and one to the right. Meet in the middle, a testicl fight!♪"
"Tea, cake or DEATH!"
"Hello IT? Have you tried turning it off and on again?"
"Oh mamá! ella me ha besado♪"
"Yes!"
"For me, it was Tuesday"
"Are you from the past?"
"Mala leche! Hay bronca en tus ojos!♪"
"I'm blue, da-ba-dee, da-ba-di♪"
"Computer updated!"
"An Unexpected Error Has Occurred."
"Un error inesperado ha ocurrido."
"Tu base de Antivirus ha sido actualizada!"
"There is no knowledge that is not power."
"Superb!"
"Excellent!"
"Outstanding!"
"FINISH HIM!"
"Flawless Victory"
"COUNTER!"
"Toasty!"
"/s"
"Totsugeki!"
"Thrash is trash, Baby!"
"F**k yo couch, Ni**a! F**K YO COUCH!"
"Coldblooded♪"
*** Bicycle kick noises ***
"If you want fast and reliable internet. Fuck you."
"I get the ball reference... but WTF?!"
"Omelette du fromage!"
"Bitches leave!"
"Vamos che!"
"FeelsBadMan"
"FeelsGoodMan"
"I never lose!"
"MORTIS"
"Do you like hurting other people?"
"Woof"
"Meow"
"Guau"
"Miau"
"Live and let die"
"Messatsu!"
"Batsuzangaisei Kikokushuushuu Yuegoukinari"
"Scislac Busorez"
"..."
"Otoko no ippatsu da, kora!"
"The answer lies in the Heart of Battle."
"Kore ga...Kusanagi no ken da!"
"GET OVER HERE!"
"Oooh... Nasty!"
uwu
owo
ewe
(╯’□’)╯︵ ┻━┻
"ATATATATATATATATATATATATATATATATATATATATATATATA"
"Hadouken!"
"ATACTACDUKEN!"
"What is a man? A miserable little pile of secrets!"
"GIT GUD!"
"YOU DIED"
"You should really try tattoy..."
"""
